project:
  type: website
  output-dir: ../docs

website:
  title: "ANNarchy tutorial"

  navbar:
    background: black
    logo: img/logowhite.png
    right:
      - text: "Slides"
        file: slides/presentation.html
      - text: "Notebooks"
        file: notebooks/Content.qmd
      - icon: github
        href: https://github.com/ANNarchy/ANNarchy
        aria-label: GitHub

  sidebar:
    style: "docked"
    logo: img/tuc-new.png
    search: true
    contents:
      - text: "About"
        file: index.qmd
      - section: "Tutorial"
        contents:
        - Neurocomp.qmd
        - ANNarchy.qmd
        - RateCoded.qmd
        - Spiking.qmd
      - section: "Notebooks"
        contents:
          - notebooks/RC.ipynb
          - notebooks/BCM.ipynb
          - notebooks/Miconi.ipynb
          - notebooks/AdEx.ipynb
          - notebooks/SynapticTransmission.ipynb
          - notebooks/COBA.ipynb
          - notebooks/STP.ipynb
          - notebooks/STDP.ipynb

  page-footer:
    center: |
      Copyright 2022 - Julien Vitay <julien.vitay@informatik.tu-chemnitz.de> - Chemnitz University of Technology

format:
  html:
    theme: [sandstone, custom.scss]
    page-layout: full
    smooth-scroll: true
    html-math-method: katex

highlight-style: github
code-line-numbers: false

filters:
  - center_images.lua
  - quarto

